---
title: "Revenue Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyr)
library(dplyr)
library(shiny)
library(plotly)
```

```{r}
#source files
source('./simulatedData.R', local = T)
```

```{r}
#import source data
revenueData <- sourceData()
```

Budget Variance
=======================================================================

Sidebar {.sidebar data-width=200}
-----------------------------------------------------------------------
```{r}
#drop down for YTD/MTD
selectInput('ytdMtd', 'Select Period Type',
            choices = c('YTD', 'MTD'),
            selected = 'YTD')

#date input for UI
dateInput('dateLimit', 'Select date', value = as.Date('2018-01-01'), 
          min = min(revenueData$date), max = as.Date(Sys.Date()))

```

```{r}
#common filtering for data
filteredData <- 
  reactive({revenueData %>%
    {if (input$ytdMtd == 'YTD') 
      filter(., as.Date(date, origin = "1970-01-01") >= as.Date(
        input$dateLimit, origin = "1970-01-01") %>%
    format("%Y-01-01"))
      else
        filter(., as.Date(date, origin = "1970-01-01") >= as.Date(
          input$dateLimit, origin = "1970-01-01") %>%
            format("%Y-%m-01"))}
  })
```


Row {data-height=500}
-----------------------------------------------------------------------
### **Revenue Gap across Departments**
```{r}
renderPlotly({
  actualRev <- filteredData() %>%
  select(date, ends_with('Actual')) %>%
  gather(key = "DepartmentActual", value = "ActualRevenue", contains('Actual')) %>%
  mutate(Department = gsub('Actual', '', DepartmentActual)) 
 
  
budgetRev <- filteredData() %>%
  select(date, ends_with('Budget')) %>%
  gather(key = "DepartmentBudget", value = "BudgetRevenue", contains('Budget')) %>%
  mutate(Department = gsub('Budget', '', DepartmentBudget)) 

revGap <- inner_join(actualRev, budgetRev,
               by = c('date', 'Department')) %>%
  mutate(RevenueGap = ActualRevenue-BudgetRevenue) %>%
  #select(one_of('Department', 'RevenueGap')) %>%
  #group_by(Department) %>%
  summarise(RevenueGap = sum(RevenueGap))
  
  p <- plot_ly(revGap, 
               x = 'All Departments', 
               y = ~RevenueGap,
  name = "Revenue Gap",
  type = "bar",
  #orientation = 'h',
   marker = list(
      color = 'rgba(71, 58, 131, 0.8)'
    )
  ) %>%
    layout(paper_bgcolor = 'rgb(248, 248, 255)', 
           plot_bgcolor = 'rgb(248, 248, 255)',
           yaxis = list(title = 'Revenue Gap'))
  })
```


### **Department revenue and Percent Margin**
```{r}
renderPlotly({
  actualRev <- filteredData() %>%
  select(date, ends_with('Actual')) %>%
  gather(key = "DepartmentActual", value = "ActualRevenue", contains('Actual')) %>%
  mutate(Department = gsub('Actual', '', DepartmentActual)) 
 
  
  budgetRev <- filteredData() %>%
    select(date, ends_with('Budget')) %>%
    gather(key = "DepartmentBudget", value = "BudgetRevenue", 
           contains('Budget')) %>%
    mutate(Department = gsub('Budget', '', DepartmentBudget)) 

  actualVsRevenue <- inner_join(actualRev, budgetRev,
                by = c('date', 'Department')) %>%
    select(one_of('Department', 'ActualRevenue', 'BudgetRevenue')) %>%
    group_by(Department) %>%
    summarise(ActualRevenue = sum(ActualRevenue), 
                BudgetRevenue = sum(BudgetRevenue))
  
  p <- plot_ly(actualVsRevenue, 
               x = ~Department, y = ~ActualRevenue,
  name = "Actual Revenue",
  type = "bar",
  marker = list(
    color = 'rgb(55, 83, 109)'
  )
) %>%
    add_trace(y = ~BudgetRevenue, name = 'BudgetRevenue', 
              marker = list(color = 'rgb(26, 118, 255)')) %>%
    layout(yaxis = list(title = 'Budget/Actual Revenue'))
  
  
  #data and plot for percent margin
   percentMargin <- inner_join(actualRev, budgetRev,
                       by = c('date', 'Department')) %>%
    mutate(RevenueGap = ActualRevenue-BudgetRevenue) %>%
    select(one_of('Department', 'RevenueGap', 'BudgetRevenue')) %>%
    group_by(Department) %>%
    summarise(MarginPercent = sum(RevenueGap)*100.00/sum(BudgetRevenue))
  
  ay <- list(
  tickfont = list(color = "red"),
  overlaying = "y",
  side = "right",
  title = "Revenue Margin(%)"
  )

  p <- p %>%
    add_trace(x = ~percentMargin$Department, y = ~percentMargin$MarginPercent, 
              type = "scatter",
              name = "Revenue Margin(%)",
              mode = 'lines+markers', yaxis = "y2",
              line = list(
      color = 'rgb(255,165,0)'
    ),
    marker = list(
      color = 'rgb(255,165,0)'
    )
    ) %>%
    layout(yaxis2=ay,
           legend = list(x = 1.2, y = 1.2, orientation = 'h'),
           paper_bgcolor = 'rgb(248, 248, 255)', 
           plot_bgcolor = 'rgb(248, 248, 255)')
  p})
```

Row
--------------------------------------------------------------------------------

Data Source
=======================================================================
```{r}
DT::datatable(revenueData, options = list(
  pageLength = 25
))
```

